# Generated by Django 5.0.3 on 2024-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorierecipe',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
